### ISSUE TITLE
Voting ? or ∞ brings up NaN when calculating averages

### ISSUE THREAD

**Issue by gaktive** [aalves08/poker-tool#11]
Great tool!

When the question mark or infinity symbol are included as part of voting, the way that averages are calculated doesn't know they're not numbers, so when completing the vote, NaN becomes the average.

**Comment by gaktive** [comment]
#9 or #10 appear to tackle this in similar ways.

**Comment by aalves08** [comment]
Gonna close this issue as it should be fixed by https://github.com/aalves08/poker-tool/pull/10 which has been merged
